import fs from 'node:fs';
const r=p=>fs.readFileSync(p,'utf8');
const main=r('src/main.js'),ann=r('src/annotations.js'),eng=r('src/drawing_engine.js'),layout=r('src/module_layout.js'),lab=r('src/structure_case_lab.js'),html=r('index.html');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(layout.includes("M01','市场工作台")||layout.includes("id:'M01',title:'市场工作台'"),'M01 Chinese workspace missing');
ok(layout.includes("id:'M02',title:'结构研究工作台'"),'M02 merged workspace missing');
for(const removed of ['M03','M04','M05','M06'])ok(!layout.includes(`id:'${removed}'`),`removed top-level module remains: ${removed}`);
ok(!layout.includes("target:'#researchPanel'"),'M03 replay target remains');
ok(!html.includes('id="researchPanel"'),'M03 replay panel remains');
ok(ann.includes('redoDrawing'),'redo missing');
ok(ann.includes("return includeCrossTimeframe&&['trend','horizontal'].includes(x.type)"),'cross-timeframe same-object view missing');
ok(eng.includes("kind:'suggestion'"),'non-blocking smart calibration missing');
ok(eng.includes('api.onCommit?.(drawingObj);'),'trendline is not committed immediately');
ok(main.includes("e.altKey&&e.key.toLowerCase()==='t'"),'Alt+T missing');
ok(main.includes("e.altKey&&e.key.toLowerCase()==='h'"),'Alt+H missing');
ok(main.includes('resolveTrendStyle(d)'),'shared trend style missing');
ok(!main.includes("projected?'#6f8da8'"),'projected grey trendline remains');
ok(!main.includes("currentTF=$('#timeframe').value;selectedDrawingId=null"),'timeframe still clears selected drawing');
ok(main.includes('drawingFloatBar'),'floating drawing toolbar integration missing');
ok(lab.includes('trendlineRef'), 'M02 case live drawing reference missing');
ok(lab.includes('scanStale'), 'structure-change stale scan flag missing');
ok(html.includes('案例研究记录'), 'Chinese case history title missing');
console.log('WORKSPACE_CONVERGENCE_V1_SMOKE_OK');
